### PR TITLE
Single sign on

### PR DESCRIPTION
**Pull request by lee-kagiso**
- Replace CAS references with 'Auth' as acronyms aren't team friendly
- Staff members dont need to confirm email addresses
- Track app from where users sign up from and where they last sign in to
- Reduce dependencies on local user existing, and treat auth api user as the canonical user
- Support settings as lambdas that take a request param

[Review on Reviewable](https://reviewable.io/reviews/kagiso-future-media/django_auth/35)

### CODE REVIEW

**Comment by lee-kagiso** [comment]
Please don't merge yet, as everything has to be deployed in lockstep

**Comment by colinfrankb** [comment]
Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: 3 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kagiso-future-media/django_auth/35)*

**Comment by colinfrankb** [comment]
*[kagiso_auth/tests/unit/test_views.py, line 262 \[r3\]](https://reviewable.io:443/reviews/kagiso-future-media/django_auth/35#-K4XyFtpqz6R8LWAJmer:-K4XyFtpqz6R8LWAJmes:-1624077336) ([raw file](https://github.com/kagiso-future-media/django_auth/blob/c52565d9150c0f4e662b327548980737f4927c50/kagiso_auth/tests/unit/test_views.py#L262)):*
`mock_result` is not actually being used?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kagiso-future-media/django_auth/35)*

**Comment by lee-kagiso** [comment]
Review status: 3 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[kagiso_auth/tests/unit/test_views.py, line 262 \[r3\]](https://reviewable.io:443/reviews/kagiso-future-media/django_auth/35#-K4XyFtpqz6R8LWAJmer:-K4aUPbPxFqxobV_nK80:-1682498492) ([raw file](https://github.com/kagiso-future-media/django_auth/blob/c52565d9150c0f4e662b327548980737f4927c50/kagiso_auth/tests/unit/test_views.py#L262)):*
It is, in the view it gets error=True, I am just not making assertions against it here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kagiso-future-media/django_auth/35)*

**Comment by lee-kagiso** [comment]
so now only 1 of your comments is on reviewable and the rest here, that is making things tough

**Comment by lee-kagiso** [comment]
```

the way i read exists_in_auth_db tells me that im expecting true or false..

yet, a user instance is returned .. i think this could be named better..

how about get_user_from_auth_db
```

Agreed

**Comment by lee-kagiso** [comment]
```

This method doesn't really "sync" from anywhere, as all you doing is passing the data you want to save.

From reading sync from auth db tells me that this function will go and call the auth db.
```

It does sync, it gets the canonical data from the auth api, and either creates or updates the local copy

**Comment by lee-kagiso** [comment]
```

How will the settings.APP_NAME function look for the cms?

I assume you will be checking if its jac, ecr or the admin section, return the relevant app name, or will be only be using two app names now?
```

settings may be lambdas that take a request arg, so the lambda can then work out the value depending on site_name context processor

**Comment by colinfrankb** [comment]
```
def sync_from_auth_db_locally(data):
        try:
            pre_save.disconnect(
                save_user_to_auth_api,
                sender=KagisoUser
            )
            user = KagisoUser()
            user.build_from_auth_api_data(data)
            user.save()
            return user
        finally:
            pre_save.connect(save_user_to_auth_api, sender=KagisoUser)
```

`It does sync, it gets the canonical data from the auth api, and either creates or updates the local copy`

I disagree, it uses the data passed in, so the name of the function doesn't make sense

**Comment by colinfrankb** [comment]
Which is why i suggested placing your following code in there as well
`user = KagisoUser.objects.filter(id=data['id']).first()`

**Comment by lee-kagiso** [comment]
So what does that do? currently if the user doesnt exist it creates the user, else it updates the user

**Comment by lee-kagiso** [comment]
oh i see, that might make some drama, going to do some manual testing due to the nature of this pr, so it will crop up then if there is any hassle

**Comment by colinfrankb** [comment]
okay cool, feel free to self merge in what order your PR's need to be merged in

**Comment by lee-kagiso** [comment]
``````
def sync_from_auth_db_locally(data):
        try:
            pre_save.disconnect(
                save_user_to_auth_api,
                sender=KagisoUser
            )
            user = KagisoUser()
            user.build_from_auth_api_data(data)
            user.save()
            return user
        finally:
            pre_save.connect(save_user_to_auth_api, sender=KagisoUser)
```

`It does sync, it gets the canonical data from the auth api, and either creates or updates the local copy`

I disagree, it uses the data passed in, so the name of the function doesn't make sense
```
ok i see, what you are talking about, i will review the naming now

**Pull request merged**
